/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-primary": "#00363a",
        "on-primary-fixed": "#002022",
        "surface-tint": "#00dbe9",
        "surface-container": "#201f1f",
        "on-secondary-fixed-variant": "#5e4200",
        "on-primary-fixed-variant": "#004f54",
        "surface-container-low": "#1c1b1b",
        "primary-container": "#00f0ff",
        "outline": "#849495",
        "on-error": "#690005",
        "secondary-fixed": "#ffdea8",
        "surface-dim": "#131313",
        "on-surface-variant": "#b9cacb",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-primary-container": "#006970",
        "tertiary-container": "#ebcfff",
        "primary-fixed-dim": "#00dbe9",
        "on-tertiary-container": "#8d00e5",
        "primary": "#dbfcff",
        "background": "#131313",
        "inverse-surface": "#e5e2e1",
        "outline-variant": "#3b494b",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "inverse-on-surface": "#313030",
        "primary-fixed": "#7df4ff",
        "secondary-container": "#feb700",
        "on-tertiary-fixed": "#2d004f",
        "on-tertiary": "#4b007e",
        "on-secondary-container": "#6b4b00",
        "on-secondary": "#412d00",
        "inverse-primary": "#006970",
        "secondary": "#ffdb9d",
        "surface": "#131313",
        "on-surface": "#e5e2e1",
        "secondary-fixed-dim": "#ffba20",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#dfb7ff",
        "surface-variant": "#353534",
        "tertiary": "#fdf2ff",
        "surface-bright": "#3a3939",
        "tertiary-fixed": "#f1daff",
        "on-tertiary-fixed-variant": "#6b00b0",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary-fixed": "#271900",
        "on-background": "#e5e2e1"
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        mono: ["Geist Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
